checksumBehavior: update

packageExtensions:
  cypress@*:
    peerDependencies:
      lodash: "*"
  webpack-dev-server@*:
    peerDependencies:
      optional: true
      webpack-cli: "*"
  webpack@*:
    peerDependencies:
      webpack-cli: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-rc.js
